# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 181c0eb32e24b07199b727dd540b945cce8c6a3ca316740b4b30af5e859b75ab11291354a1c43b730f32af4bbb151d26eb6f9f0731385e7a36c6d1d295d8a04e

test:
  secret_key_base: b351f2c16fce14567afff86a6d1a761b697933fbcaab23e6a2293bca11bf48eefd327d2e354aa0a53a60de005f6783cee97b4ccaf8c6b52451f1ceff8b706dca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
